server:
   port: 8081

spring:
   data:
      mongo:
         host: localhost
         port: 27017
         database: employee
         
logging:
  level:
    org:
      springframework:
        security: DEBUG